### ISSUE TITLE
Subtitle Support

### ISSUE THREAD

**Issue by sbilketay** [andrefilimono/clappr-flvjs-playback#1]
Hello there. Nice project, thank you. Is it possible to add a subtitle file to this video player?

**Comment by andrefilimono** [comment]
Yeah, I released a new version of the plugin so you can attach external subtitles by setting [externalTracks](https://github.com/clappr/clappr/blob/master/doc/BUILTIN_PLUGINS.md#playback-configuration) property of `playback`.

But it works correctly `only` for `VOD` streams.
