### ISSUE TITLE
not working in ie10/11

### ISSUE THREAD

**Issue by wanstonq** [andrefilimono/clappr-flvjs-playback#2]
flvjs-playback plugin not working in  ie10/11

**Comment by ranst91** [comment]
After checking this issue in dept. It seems as flv.js as it is used in this plugin, does not have proper es5 transpiling.
However, the same package, consumed through their CDN is transpiled correctly and supports ie11. Therefore, currently getting flv.js as npm package will cause this issue.

**Comment by andrefilimono** [comment]
I've excluded flv.js from the build.
@ranst91 Thanks for the help!
