### ISSUE TITLE
Disbale flv plugin logs

### ISSUE THREAD

**Issue by ranst91** [andrefilimono/clappr-flvjs-playback#3]
The plug in seems to log everything it does and my console is heavily spammed with things like:
"[MSEController] > Received Initialization Segment, mimeType: video/mp4;codecs=avc1.42801f"
and similar.
Since the only configuration stated is this table: https://github.com/Bilibili/flv.js/blob/master/docs/api.md#config
I couldn't locate where can I turn this off.

Any help?

**Comment by andrefilimono** [comment]
Hi, thanks for the Issue :)
I've released a new version of the plugin, so flv.js logging is disabled by default, but it can be enabled with the "enableLogging" option.
