### ISSUE TITLE
The live stream style is not using the dvr-control style of clappr

### ISSUE THREAD

**Issue by amhoho** [andrefilimono/clappr-flvjs-playback#8]
Play hls live stream in clappr,control style(dvr-control):
play/stop live volume fullscreen
use clappr-flvjs-playback,control style:
play/stop 00:00:01|--:-- volume fullscreen

**Comment by andrefilimono** [comment]
Hi, if I understand the problem correctly, then to get displayed a LIVE icon in media control in case of live FLV.js stream you should pass the **isLive: true** parameter to the flvjs configuration object as follows:
```js
var player = new Clappr.Player({
  source: "URL to LIVE FLV stream",
  mimeType: 'video/flv',
  plugins: [
    FLVPlayback
  ],
  playback: {
    flvjsConfig: {
      isLive: true <-- THIS LINE
    }
  }
});
```

**Comment by amhoho** [comment]
thanks
